### PR TITLE
JSON for topics

### LINKED ISSUE #23: video metadata
json feed that provides the following:

For the next meeting meeting:
Group Name: "ChIPy"
Event Name: "April 2012 Meeting"

For each talk:
Presenter(s):
Contact email(s):
Title:
Start time:
Duration:
Description:
Released: yes/no.

Here is the app that consumes the data:
https://github.com/CarlFK/veyepar/blob/master/dj/scripts/addeps.py

### PR DESCRIPTION
**Pull request by emperorcezar**
Attempting to fix #23

So I noticed that you have models in there for topics and such. I've stuck some JSON in front of it. I just want an opinion on how I should handle starttime for a topic.
### Options
1. There is no order, so I can randomly assign an order and extrapolate a start time. This probably makes the start time useless to Carl.
2. Add order field to topics. I don't see where to put a migration, so I'm assuming you're not using South? If I do this, do you want to have verification that the order is unique among topic in the same meeting. So, put in the code so that there aren't two topics with order of 1.

### CODE REVIEW

**Comment by brianray** [comment]
Questions for @CarlFK

**Comment by CarlFK** [comment]
1. Add start time and duration.
   This will help allocate times and stuff, like "This talk gets 30 min, this one 15."

(jhey github, that's a 3 up there, why you put a 1?)

**Comment by emperorcezar** [comment]
@CarlFK I don't think you understand. A meeting is attached to a topic, the meeting has a start time. The topics also have a duration. I need an order of the talks to figure out the start time of the talks.

Unless you mean I give topics start times also?

**Comment by CarlFK** [comment]
> Unless you mean I give topics start times also?

yes.

If you use duration, then every block of time has to be allocated, including the meeting start, breat, pizza, book give-away, etc.   giving each a start time lets that be set to whatever, and some judgement as to what it should be.  

Pluse it seems the easiest way, and I dount see how it would cause a problem.  "meeting start" is pretty much a constant.

**Comment by emperorcezar** [comment]
Ok. That sounds reasonable. I'll go ahead and do that.

On Sun, Apr 8, 2012 at 11:20 PM, Carl Karsten <
reply@reply.github.com

**Comment by emperorcezar** [comment]
@brianray How do you want a migration handled on that? Are you just going to do it by hand?

**Comment by brianray** [comment]
I can not do a push to production between now and the meeting; however, your more than welcome. Also Daniel Peters showed some interests in helping this week.

**Comment by emperorcezar** [comment]
@brianray I mean the db migration. I didn't see south in the code base so I was wondering if you wanted me to write up the sql migration or if you were just going to go into your db and do it by hand?

**Comment by brianray** [comment]
I honestly do not recall if we have south here or not. My guess is your right, no south. I would be ok with a .sql file for migration, personally; however, please note that we use mysql in production, evident from the settings.py

**Comment by emperorcezar** [comment]
@brianray Double check my sql if you could?

**Comment by brianray** [comment]
what are you asking? please elaborate

**Comment by emperorcezar** [comment]
Just so someone will double check it. I don't have mysql on my macbook.

**Comment by brianray** [comment]
where is it?

**Comment by emperorcezar** [comment]
@brianray In the diff or in meetings/migrations/001.sql

**Comment by brianray** [comment]
I am really not a fan of keeping a start_time. I would prefer to tell someone how long they have and have a totally unstructured amount of time between presentations or just let a good one run longer.  Must we have a start_time?

**Comment by emperorcezar** [comment]
I think the start time is more to help @CarlFK software and not something we have to enforce of speakers. I'm sure Carl could go into more detail. I believe that he records the whole thing and the starttime lets his software tell him where to look to split that video.

So. It's just a guess and it's not something we have to enforce of speakers.

**Comment by brianray** [comment]
got it, ok. I will test this SQL and get back to you.

**Comment by dtpeters** [comment]
@emperorcezar yeah, south isn't included yet, but it will be after I've upgraded to the latest release of pinax. do whatever you have to do and I'll follow behind man.

**Comment by emperorcezar** [comment]
@dtpeters For now just do the migration by hand instead of waiting for south. That way we can make Carl happy. We all love a happy Carl.

**Comment by dtpeters** [comment]
@emperorcezar  "we all love a happy carl"  == truth

**Comment by emperorcezar** [comment]
Ok, just let me know when you're ready for merge.

**Comment by brianray** [comment]
OK, merged! I badly need someone to deploy this on chipy.org I'm simply too busy this week. Anyone?

**Comment by dtpeters** [comment]
I can get you. can it hold it until tomorrow night?

On Sat, Apr 14, 2012 at 8:12 AM, Brian Ray <
reply@reply.github.com

**Comment by CarlFK** [comment]
sure - it can pretty much wait till someone puts in some data for next
months meeting.

On Sat, Apr 14, 2012 at 11:13 AM, Daniel Peters <
reply@reply.github.com

> wrote:
> 
> I can get you. can it hold it until tomorrow night?
> 
> On Sat, Apr 14, 2012 at 8:12 AM, Brian Ray <
> reply@reply.github.com
> 
> > wrote:
> > 
> > OK, merged! I badly need someone to deploy this on chipy.org I'm simply
> > too busy this week. Anyone?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/brianray/Chipy/pull/24#issuecomment-5131208
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/brianray/Chipy/pull/24#issuecomment-5132381

## 

Carl K

**Comment by dtpeters** [comment]
sweet, it won't have to wait that long :P

On Sat, Apr 14, 2012 at 11:15 AM, Carl Karsten <
reply@reply.github.com

**Pull request merged**
